@echo off
echo Cleaning and reinstalling frontend dependencies...
cd frontend
echo Removing node_modules...
rmdir /s /q node_modules 2>nul
echo Removing package-lock.json...
del package-lock.json 2>nul
echo Installing dependencies...
call npm install --legacy-peer-deps
echo Starting frontend...
call npm start
pause
