version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-thewho_prod}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - crm-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.beget
    container_name: crm-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-thewho_prod}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - crm-network
    depends_on:
      - postgres

  # Frontend
  frontend:
    image: nginx:alpine
    container_name: crm-frontend
    restart: unless-stopped
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/beget.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - crm-network

volumes:
  postgres_data:
    driver: local

networks:
  crm-network:
    driver: bridge
