version: '3.8'

services:
  # Backend API with Supabase
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.beget
    container_name: crm-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5100
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      SSL_ENABLED: "true"
      TYPEORM_SYNCHRONIZE: "false"
      TYPEORM_LOGGING: "true"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "127.0.0.1:5100:5100"
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend
  frontend:
    image: nginx:alpine
    container_name: crm-frontend
    restart: unless-stopped
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/beget-supabase.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:5101:80"
    networks:
      - crm-network
    depends_on:
      - backend

networks:
  crm-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local
  logs_data:
    driver: local
