@echo off
echo Fixing frontend dependencies...
cd frontend
echo Adding missing ajv dependency...
call npm install ajv@^8.12.0 --save-dev --legacy-peer-deps
echo Starting frontend...
call npm start
pause
