# Фильтр для обнаружения подозрительных User-Agent
[Definition]
failregex = ^<HOST>.*"(nmap|nikto|wikto|sf|sqlmap|bsqlbf|w3af|acunetix|havij|appscan|burp|masscan|dirb|gobuster|dirbuster|hydra|metasploit|nessus|openvas|nuclei|scrapy)".*$

ignoreregex = 

datepattern = ^%%Y/%%m/%%d %%H:%%M:%%S
